### ISSUE TITLE
process-hollow example doesn't run

### ISSUE THREAD

**Issue by Teach2Breach** [2vg/blackcat-rs#3]
thread 'main' panicked at 'cannot transmute_copy if U is larger than T', /rustc/17cbdfd07178349d0a3cecb8e7dde8f915666ced\library\core\src\mem\mod.rs:1057:5

**Comment by 2vg** [comment]
Thanks for reporting, I will check it later days.

**Comment by 2vg** [comment]
fixed.

**Comment by Teach2Breach** [comment]
hey thanks! I tried to fix it and PR but couldn't seem to get it work. I'm excited to see how you solved the issue. Thanks again for jumping right on this issue! I wasn't sure if the project was still active. You have fantastic repos by the way. Thanks for sharing.

**Comment by Teach2Breach** [comment]
also, I can confirm, it does work for me now.
